swagger: "2.0"
info:
  description: "配置服务服务端API."
  version: 1.0.0
  title: 配置服务服务端API
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: config.api.lucfish.com
basePath: /
tags:
  - name: config
    description: ""
schemes:
  - https
paths:
  /config/create:
    post:
      tags:
        - config
      summary: 创建配置
      description: 创建配置
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/CreateConfigReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse_Config"
  /config/update:
    post:
      tags:
        - config
      summary: 更新配置
      description: 更新配置
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateConfigReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse_Config"
definitions:
  CreateConfigReq:
    title: CreateConfigReq
    type: object
    properties:
      tenantId:
        type: string
      referId:
        type: string
      templateId:
        type: integer
        format: int64
      key:
        type: string
      value:
        type: string
  APIResponse_Config:
    allOf:
      - $ref: "#/definitions/APIResponse"
      - type: object
        properties:
          data:
            $ref: "#/definitions/Config"
  UpdateConfigReq:
    title: UpdateConfigReq
    type: object
    properties:
      id:
        type: integer
        format: int64
      value:
        type: string
  UpdateConfigRsp:
    title: UpdateConfigRsp
    type: object
    properties:

  Config:
    type: object
    properties:
      id:
        type: integer
        format: int64
      tenantId:
        type: string
      referId:
        type: string
      templateId:
        type: integer
        format: int64
      key:
        type: string
      value:
        type: string
      ctime:
        type: integer
        format: int64
      mtime:
        type: integer
        format: int64
  APIResponse:
    title:
    description:
    type: object
    properties:
      errcode:
        type: integer
        format: int32
      errmsg:
        type: string
